development:
    cloud_name:  dymyyh3bj
    api_key:  366627257786553
    api_secret:  l3KQLgQrQkCTfBM2rCH2ypksYZo

production:
    cloud_name:  dymyyh3bj
    api_key:  366627257786553
    api_secret:  l3KQLgQrQkCTfBM2rCH2ypksYZo